//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MasterFirm
    {
        public decimal FID { get; set; }
        public string FName { get; set; }
        public string FAddress { get; set; }
        public Nullable<decimal> Contact { get; set; }
        public string GSTN { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
    }
}
