//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Master_Frm
    {
        public decimal Id { get; set; }
        public string FrmName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string GSTIN { get; set; }
        public string State { get; set; }
        public string StateCode { get; set; }
    }
}
