//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Temp_Purchase_Details
    {
        public decimal Id { get; set; }
        public string KeyId { get; set; }
        public Nullable<decimal> ItemId { get; set; }
        public string Unit { get; set; }
        public string Pack { get; set; }
        public string Batch { get; set; }
        public string Expiry { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> Edit { get; set; }
        public Nullable<decimal> DeleteId { get; set; }
    }
}
