//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Purchase
    {
        public decimal Id { get; set; }
        public Nullable<decimal> VN { get; set; }
        public string Date { get; set; }
        public Nullable<decimal> InvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<decimal> Supplierid { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> uid { get; set; }
        public string Session { get; set; }
        public Nullable<decimal> DFlag { get; set; }
        public string Cdate { get; set; }
    }
}
