//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Master_Item
    {
        public decimal Id { get; set; }
        public Nullable<decimal> CompanyId { get; set; }
        public Nullable<decimal> CategoryId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> UnitId { get; set; }
        public Nullable<decimal> Pack { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Disc { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Reorder { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> OpeningQty { get; set; }
        public string Batch { get; set; }
        public string Expiry { get; set; }
        public Nullable<decimal> PCSRate { get; set; }
        public Nullable<decimal> Uid { get; set; }
        public string Session { get; set; }
        public string Date { get; set; }
        public string CDate { get; set; }
        public string Time { get; set; }
        public string Ip { get; set; }
        public Nullable<decimal> DFlag { get; set; }
        public Nullable<decimal> UpdateBy { get; set; }
        public string UpdateDate { get; set; }
        public string UpdateTime { get; set; }
    }
}
